services:
  postgres:
    image: postgres:latest
    restart: ""
    ports:
      - "2040:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres_database:/var/lib/postgresql/data:Z

  rabbitmq:
    container_name: c_rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest 
    volumes:
      - rabbitmq:/var/lib/rabbitmq
 
volumes:
  postgres_database:
  rabbitmq: